% -------------------------------------------------------------------
%  Generated by MATLAB on 10-Jan-2023 16:54:04
%  MATLAB version: 9.10.0.1602886 (R2021a)
% -------------------------------------------------------------------
clc,clear;
syms b_at K_sat K_siat
%saveVarsMat = load('WorkspaceData.mat');

%||================================||
%|| Parámetros del Sistema Físico  ||
%||================================||
Y_t0 = 45;                  %m Altura (fija) de poleas de suspensión de Izaje en el Carro (desde el nivel de muelle).
H_c = 2.5;                  %m Alto y ancho de Container Estándar (aprox., normalizado: ISO Containers).
M_s = 15000;                %kg Masa de Spreader + Headblock (sin container).
M_cmax = 70000;             %kg Masa nominal de Container/s a izar (máxima totalmente cargado).
M_cmin = 2000;              %kg Masa de Container Estándar vacío (mínima, sin carga interna).
g = 9.80665;                %m/s^2. Aceleración de la gravedad 
M_real = 40000;
constante_frenos=10;

%||================================||
%||        Variables Izaje         ||
%||================================||
r_hd = 0.75;                %m
i_h = 22;                   %22∶1
J_hdhEb = 3800;             %kg.m^2
J_hmhb = 30;                %kg.m^2
b_hEb = 2.2E+9;             %N.m/(rad/s)
b_hb = 1.0E+8;              %N.m/(rad/s)
b_hd = 8;                   %N.m/(rad/s)
b_hm = 18;                  %N.m/(rad/s)
b_wu = 1500;                 %N/(m/s)/m
k_wu = 2.36E+9;             %(N/m)*m
%out = saveVarsMat.out;      % <1x1 Simulink.SimulationOutput> unsupported class
T_hbMax = 5e4;              %N.m
T_hEbMax = 1.1e6;           %N.m
tau_hm = 1e-3;              %ms

a_l_max=0.75;               %m/s^2


%||================================||
%||        Variables carro         ||
%||================================||
r_td = 0.5;                 %m
i_t = 30;                   %30∶1
J_td = 1200;                %kg.m^2
J_tmtb = 7;                 %kg.m^2
b_td = 1.8;                 %N.m/(rad/s)
b_tm = 6;                   %N.m/(rad/s)
b_tb = 5e6;                 %N.m/(rad/s)
T_tbmax = 5e3;              %N.m 
T_tmmax = 3e3;              %N.m 
tau_tm = 1e-3;              %ms

v_t_max = 4;                %m/s
a_t_max =0.8;               %m/s^2
w_tm_min = 20;              %rad/s


%||=======================================||
%|| Carga apoyada, parámetros de contacto ||
%||=======================================||
K_cy = 1.8e9;                 %N/m. Rigidez de compresión por contacto vertical (carga comprime apoyo).
b_cy = 1e7;                   %N.s/m. Fricción interna o amortiguamiento de compresión por contacto vertical.
b_cx = 1e6;                   %N.s/m. Fricción de arrastre horizontal por contacto vertical.


%||================================||
%||     Carro y cable de acero     ||
%||================================||
M_t = 30000;                  %kg.   Masa equivalente de Carro, ruedas, etc..
b_t = 90;                     %Nm/s. Coeficiente de Fricción mecánica viscosa equivalente del Carro.
K_tw = 4.8e5;                 %N/m.  Rigidez equivalente total a tracción de cable tensado de carro.
b_tw = 3.0e3;                 %Nm/s. Fricción interna o amortiguamiento total de cable tensado de carro.


%||================================||
%||         Controladores          ||
%||================================||
T_s2 = 5e-3;
T_s1 = 20e-3;
T_s0 = T_s1;


%||================================||
%||     Controlador de izaje       ||
%||================================||
 
ml_prueba = M_real + M_s;

J_eqh = (2/r_hd)*(J_hmhb*i_h^2+J_hdhEb);
b_eqh = (2/r_hd)*(b_hm*i_h^2+b_hd);
coef = [(-1/i_h)*(J_eqh+ml_prueba*r_hd/2); (-1/i_h)*b_eqh; 0];
polos_h = roots(coef);

w_posh = 10*polos_h(2);
n_h = 2.9;
b_ah = -(b_eqh/i_h - n_h*w_posh*J_eqh/i_h);
K_sah = -n_h*w_posh^2*J_eqh/i_h;
K_siah = w_posh^3*J_eqh/i_h ;
roots([1; (b_eqh/i_h-b_ah)/(J_eqh/i_h); -K_sah/(J_eqh/i_h); -K_siah/(J_eqh/i_h)]);


%||================================||
%||      Controlador de carro      ||
%||================================||

J_eqt = J_tmtb*i_t^2/r_td^2 + J_td/r_td^2 + ml_prueba;   
b_eqt = b_tm*i_t^2/r_td^2 + b_td/r_td^2;

coef_t = [r_td*(J_eqt+M_t)/i_t; r_td*(b_eqt+b_t)/i_t; 0];
polos_t = roots(coef_t)

w_t = 5*polos_t(2)
n_t = 2.5;

a = (r_td*b_t/i_t + r_td*b_eqt/i_t + b_at)/(r_td*(M_t+J_eqt)/i_t);
b = K_sat/(r_td*(M_t+J_eqt)/i_t);
c = K_siat/(r_td*(M_t+J_eqt)/i_t);
G_tranf = [a b c];
polin_sint_serie = [n_t*w_t  n_t*w_t^2  w_t^3];

soluc = solve([G_tranf==polin_sint_serie], [b_at, K_sat, K_siat]);
b_at = -double(soluc.b_at)
K_sat = double(soluc.K_sat)
K_siat = -double(soluc.K_siat)

roots([1; (r_td*b_t/i_t + r_td*b_eqt/i_t + b_at)/(r_td*(M_t+J_eqt)/i_t); K_sat/(r_td*(M_t+J_eqt)/i_t); K_siat/(r_td*(M_t+J_eqt)/i_t)]);


%||================================||
%||     Controlador de balanceo    ||
%||================================||

J_eqb = M_t + ml_prueba + J_tmtb*i_t^2/r_td^2 + J_td/r_td^2; % Es igual a J_eqt
b_eqb = b_t + b_tm*i_t^2/r_td^2 + b_td/r_td^2;
n_b = 2.5;


%||================================||
%||       Objetos a graficar       ||
%||================================||
%PERFIL DE OBSTÁCULOS
y_c0 = [ 0 2.5 2.5 0 5 7.5 7.5 2.5 2.5 2.5 0 15 0 7.5 17.5 20 20 12.5 15 25 25 25 5 7.5 2.5 7.5 -2.5 -5 -2.5 5 12.5 10 0];
x_c0 = -30:2.5:50;     
xx_c0 = -30:0.01:50;     % Paso cada 1cm
Y_c0 = interp1(x_c0,y_c0,xx_c0,'previous'); 
Y_c0_modif = Y_c0;

%MUELLE
my_c0 = [0 0 0 0 0 0 0 0 0 0 0 0 0 15 -20];
mx_c0 = -35:2.5:0;     
muelle_x = -35:0.01:0;     % Paso cada 1cm
muelle_y = interp1(mx_c0,my_c0,muelle_x,'previous'); 

%BARCO
by_c0 = [0 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 0];
bx_c0 = 0:2.5:50;  
barco_x = 0:0.01:50;     % Paso cada 1cm
barco_y = interp1(bx_c0,by_c0,barco_x,'previous');

%FINES DE CARRERA
F_I_n_x=ones(1,5)*-30;
F_I_n_y=43:1:47;
F_I_u_x=ones(1,5)*-33;
F_I_u_y=43:1:47;
F_D_n_x=ones(1,5)*50;
F_D_n_y=43:1:47;
F_D_u_x=ones(1,5)*53;
F_D_u_y=43:1:47;

%CARRO
carro_y=ones(1,20)*45;

%RIEL
riel_x=-35:1:55;
riel_y=ones(1,91)*45;


%||================================||
%||     Condiciones iniciales      ||
%||================================||
%pos_i_x = -8.5;
pos_i_x = -13.5;
%pos_i_yl = 20;
pos_i_yl = Y_c0(100*(pos_i_x+30)+1)+1; %30;
pos_i_lh = 45-pos_i_yl;


%FILTRO JOYSTICK
f=0.1;


clear saveVarsMat;